name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b93d5b1c02bb171a827d8cf885cf155068acf65733b07248dec7fceac6fb24b3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
