#.
#Common settings
[common]
	#.
	#Cobblestone generator stress
	#stress * rpm = total stress
	#Range: > -2147483648
	generatorStress = 8
	#.
	#Cobblestone generator ratio
	#Cobblestone/tick = rpm/ratio
	#Range: > -2147483648
	generatorRatio = 8

	#.
	#Cobblestone generator types
	#(Requires relaunch)
	[common.generatorsEnabled]
		#.
		#Enable limestone generator
		limestoneGeneratorEnabled = true
		#.
		#Enable basalt generator
		basaltGeneratorEnabled = true
		#.
		#Enable stone generator
		scoriaGeneratorEnabled = true
		#.
		#Enable stone generator
		stoneGeneratorEnabled = true
		#.
		#Enable cobblestone generator
		cobblestoneGeneratorEnabled = true
