[air]
	#Range: > 1
	uses_per_tank = 1024
	#Range: > 1
	uses_per_tank_hover = 4096
[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.01
	#Range: 0.01 ~ 100.0
	acceleration = 0.3
	#Range: 0.0 ~ 100.0
	swim_modifier = 0
	#Range: 0.01 ~ 100.0
	vertical = 0.2
	#Range: -100.0 ~ 0.0
	hover_descend = -0.03
[features]
	#Range: 1.0 ~ 100.0
	elytra_boost = 1
