mode = "fancy"

[light_sources]
	water_sensitive_check = true
	block_entities = false
	entities = true
	self = true
	tnt = "simple"
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = false
				bee = false
				axolotl = false
				donkey = false
				cow = false
				chest_minecart = false
				tropical_fish = false
				fox = false
				pig = false
				skeleton = false
				bat = false
				rabbit = false
				zombie = false
				drowned = false
				sheep = false
				player = true
				dolphin = false
				item = true
				turtle = false
				wolf = false
				salmon = false
				zombie_villager = false
				horse = false
				cave_spider = false
				glow_squid = false
				cod = false
				witch = false
				squid = false
				spider = false
				creeper = false
				enderman = false
				parrot = false
				ocelot = false
				slime = false
				glow_item_frame = false
				pufferfish = false
				villager = false
				cat = false
				iron_golem = false
				llama = false
				tnt_minecart = false
				guardian = false
				elder_guardian = false
				trident = false
				frog = false
				experience_orb = false
				item_frame = false
				area_effect_cloud = false
				panda = false
				goat = false
				wither_skeleton = false
				phantom = false
				potion = false
				hoglin = false
				illusioner = false
				armor_stand = false
				painting = false
				magma_cube = false
				pillager = false
				arrow = false
				vindicator = false
				ghast = false
				camel = false
				evoker_fangs = false
				evoker = false
				silverfish = false
				minecart = false
				furnace_minecart = false
				endermite = false
				lightning_bolt = false
				blaze = false
				strider = false
				piglin = false
				piglin_brute = false
				zombified_piglin = false
				vex = false
				allay = false
				ender_dragon = false
				ender_pearl = false
				polar_bear = false
				ravager = false
				snow_golem = false
				stray = false
				tnt = false
				experience_bottle = false
				skeleton_horse = false
				wandering_trader = false
				trader_llama = false
				llama_spit = false
				husk = false
				shulker = false
				warden = false
				shulker_bullet = false
				boat = false

			[light_sources.settings.entities.bewitchment]
				toad = false
				ghost = false
				owl = false
				snake = false
				raven = false

			[light_sources.settings.entities.naturalist]
				snail = false
				firefly = false
				lizard = false
				bluejay = false
				finch = false
				zebra = false
				boar = false
				vulture = false
				rhino = false
				canary = false
				giraffe = false
				bass = false
				lion = false
				cardinal = false
				duck = false
				butterfly = false
				catfish = false
				elephant = false
				alligator = false
				tortoise = false
				coral_snake = false
				robin = false
				snake = false
				sparrow = false
				rattlesnake = false
				bear = false
				deer = false
				dragonfly = false
				hippo = false
				lizard_tail = false

			[light_sources.settings.entities.artifacts]
				mimic = false

			[light_sources.settings.entities.lootr]
				lootr_minecart = false

			[light_sources.settings.entities.creeperoverhaul]
				beach_creeper = false
				cave_creeper = false
				savannah_creeper = false
				desert_creeper = false
				dripstone_creeper = false
				bamboo_creeper = false
				jungle_creeper = false
				hills_creeper = false
				badlands_creeper = false
				ocean_creeper = false
				swamp_creeper = false
				spruce_creeper = false
				snowy_creeper = false
				dark_oak_creeper = false

			[light_sources.settings.entities.ecologics]
				coconut_crab = false
				squirrel = false
				boat = false

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = false
				badlands_enderman = false
				cave_enderman = false
				desert_enderman = false
				swamp_enderman = false
				coral_enderman = false
				flower_fields_enderman = false
				corrupted_pearl = false
				snowy_enderman = false
				warped_forest_enderman = false
				crimson_forest_enderman = false
				nether_wastes_enderman = false
				end_enderman = false
				end_islands_enderman = false
				crimson_pearl = false
				soulsand_valley_enderman = false
				dark_oak_enderman = false
				windswept_hills_enderman = false
				bubble_pearl = true
				summoner_pearl = true
				icy_pearl = true

			[light_sources.settings.entities.duckling]
				duck = false

			[light_sources.settings.entities.guardvillagers]
				guard = false

			[light_sources.settings.entities.create]
				super_glue = false
				stationary_contraption = false
				potato_projectile = false
				carriage_contraption = false

			[light_sources.settings.entities.sihywtcamd]
				cobweb = false

			[light_sources.settings.entities.farmingforblockheads]
				merchant = false

			[light_sources.settings.entities.spell_engine]
				spell_area_effect = false
				spell_projectile = false

			[light_sources.settings.entities.bloomingnature]
				squirrel = false
				boar = false
				deer = false
				turkey = false
				owl = false
				pelican = false
				raccoon = false
				bison = false
				wandering_gardener = false
				red_wolf = false
				termite = false

			[light_sources.settings.entities.meadow]
				brown_bear = false
				wooly_cow = false

			[light_sources.settings.entities.exposure]
				photograph = false

			[light_sources.settings.entities.ad_astra]
				tier_1_rover = false
				tier_1_rocket = false
				lander = false
				tier_4_rocket = false
				air_vortex = false

			[light_sources.settings.entities.twigs]
				pebble = false

			[light_sources.settings.entities.bosses_of_mass_destruction]
				charged_ender_pearl = false
				soul_star = false
				lich = false
				void_blossom = false

			[light_sources.settings.entities.immersive_aircraft]
				airship = false
				cargo_airship = false
				bullet = false
				gyrodyne = false
				quadrocopter = false
				biplane = false
				warship = false

			[light_sources.settings.entities.railways]
				benchcart = false

			[light_sources.settings.entities.niftycarts]
				supply_cart = false
				animal_cart = false
				plow = false

			[light_sources.settings.entities.gag]
				mining_dynamite = false
				fishing_dynamite = false

			[light_sources.settings.entities.sleep_tight]
				bedbug = false
				bed_entity = false

			[light_sources.settings.entities.frostiful]
				packed_snowball = false
				chillager = false
				frost_tipped_arrow = false
				frostologer = false
				frost_spell = false

			[light_sources.settings.entities.aquamirae]
				anglerfish = false
				spinefish = false
				tortured_soul = false
				golden_moth = false
				maw = false

			[light_sources.settings.entities.supplementaries]
				rope_arrow = false

			[light_sources.settings.entities.botania]
				babylon_weapon = false
				mana_burst = false

			[light_sources.settings.entities.items_displayed]
				item_display = false

			[light_sources.settings.entities.vinery]
				wandering_winemaker = false
				mule = false

			[light_sources.settings.entities.betternether]
				firefly = false
				hydrogen_jellyfish = false
				naga = false
				jungle_skeleton = false
				skull = false

			[light_sources.settings.entities.terraform]
				boat = false

			[light_sources.settings.entities.smallships]
				cog = false
				brigg = false

			[light_sources.settings.entities.betterend]
				dragonfly = false
				end_fish = false
				end_slime = false
				shadow_walker = false
				cubozoa = false

			[light_sources.settings.entities.deeperdarker]
				sculk_leech = false
				shattered = false
				sculk_centipede = false
				sculk_snapper = false

			[light_sources.settings.entities.simplyswords]
				battlestandarddark = false

			[light_sources.settings.entities.the_bumblezone]
				rootmin = false
				honey_slime = false
				variant_bee = false
				beehemoth = false

			[light_sources.settings.entities.shield_overhaul]
				shield_bash_entity = true

			[light_sources.settings.entities.createdieselgenerators]
				chemical_sprayer_projectile = true

			[light_sources.settings.entities.malum]
				natural_spirit = true

			[light_sources.settings.entities.illagerinvasion]
				archivist = true
				provoker = true
				basher = true

