mode = "fancy"

[light_sources]
	water_sensitive_check = true
	block_entities = false
	entities = true
	self = true
	tnt = "simple"
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				donkey = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				pig = true
				skeleton = true
				bat = true
				rabbit = true
				zombie = true
				drowned = true
				sheep = true
				player = true
				dolphin = true
				item = true
				turtle = true
				wolf = true
				salmon = true
				zombie_villager = true
				horse = true
				cave_spider = true
				glow_squid = true
				cod = true
				witch = true
				squid = true
				spider = true
				creeper = true
				enderman = true
				parrot = true
				ocelot = true
				slime = true
				glow_item_frame = true
				pufferfish = true
				villager = true
				cat = true
				iron_golem = true
				llama = true
				tnt_minecart = true
				guardian = true
				elder_guardian = true
				trident = true
				frog = true
				experience_orb = true
				item_frame = true
				area_effect_cloud = true
				panda = true
				goat = true
				wither_skeleton = true
				phantom = true
				potion = true
				hoglin = true
				illusioner = true
				armor_stand = true
				painting = true
				magma_cube = true
				pillager = true
				arrow = true
				vindicator = true
				ghast = true
				camel = true
				evoker_fangs = true
				evoker = true
				silverfish = true
				minecart = true
				furnace_minecart = true
				endermite = true
				lightning_bolt = true
				blaze = true
				strider = true
				piglin = true
				piglin_brute = true
				zombified_piglin = true
				vex = true
				allay = true
				ender_dragon = true
				ender_pearl = true
				polar_bear = true
				ravager = true
				snow_golem = true
				stray = true
				tnt = true
				experience_bottle = true
				skeleton_horse = true
				wandering_trader = true
				trader_llama = true
				llama_spit = true
				husk = true
				shulker = true
				warden = true
				shulker_bullet = true
				boat = true

			[light_sources.settings.entities.bewitchment]
				toad = true
				ghost = true
				owl = true
				snake = true
				raven = true

			[light_sources.settings.entities.naturalist]
				snail = true
				firefly = true
				lizard = true
				bluejay = true
				finch = true
				zebra = true
				boar = true
				vulture = true
				rhino = true
				canary = true
				giraffe = true
				bass = true
				lion = true
				cardinal = true
				duck = true
				butterfly = true
				catfish = true
				elephant = true
				alligator = true
				tortoise = true
				coral_snake = true
				robin = true
				snake = true
				sparrow = true
				rattlesnake = true
				bear = true
				deer = true
				dragonfly = true
				hippo = true
				lizard_tail = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.creeperoverhaul]
				beach_creeper = true
				cave_creeper = true
				savannah_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				hills_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				swamp_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				dark_oak_creeper = true

			[light_sources.settings.entities.ecologics]
				coconut_crab = true
				squirrel = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				badlands_enderman = true
				cave_enderman = true
				desert_enderman = true
				swamp_enderman = true
				coral_enderman = true
				flower_fields_enderman = true
				corrupted_pearl = true
				snowy_enderman = true
				warped_forest_enderman = true
				crimson_forest_enderman = true
				nether_wastes_enderman = true
				end_enderman = true
				end_islands_enderman = true
				crimson_pearl = true
				soulsand_valley_enderman = true
				dark_oak_enderman = true
				windswept_hills_enderman = true

			[light_sources.settings.entities.duckling]
				duck = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.create]
				super_glue = true
				stationary_contraption = true
				potato_projectile = true
				carriage_contraption = true

			[light_sources.settings.entities.sihywtcamd]
				cobweb = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.spell_engine]
				spell_area_effect = true
				spell_projectile = true

			[light_sources.settings.entities.bloomingnature]
				squirrel = true
				boar = true
				deer = true
				turkey = true
				owl = true
				pelican = true
				raccoon = true
				bison = true
				wandering_gardener = true
				red_wolf = true
				termite = true

			[light_sources.settings.entities.meadow]
				brown_bear = true
				wooly_cow = true

			[light_sources.settings.entities.exposure]
				photograph = true

			[light_sources.settings.entities.ad_astra]
				tier_1_rover = true
				tier_1_rocket = true
				lander = true
				tier_4_rocket = true
				air_vortex = true

			[light_sources.settings.entities.twigs]
				pebble = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				charged_ender_pearl = true
				soul_star = true
				lich = true
				void_blossom = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				cargo_airship = true
				bullet = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				warship = true

			[light_sources.settings.entities.railways]
				benchcart = true

			[light_sources.settings.entities.niftycarts]
				supply_cart = true
				animal_cart = true
				plow = true

			[light_sources.settings.entities.gag]
				mining_dynamite = true
				fishing_dynamite = true

			[light_sources.settings.entities.sleep_tight]
				bedbug = true
				bed_entity = true

			[light_sources.settings.entities.frostiful]
				packed_snowball = true
				chillager = true
				frost_tipped_arrow = true
				frostologer = true
				frost_spell = true

			[light_sources.settings.entities.aquamirae]
				anglerfish = true
				spinefish = true
				tortured_soul = true
				golden_moth = true
				maw = true

			[light_sources.settings.entities.supplementaries]
				rope_arrow = true

			[light_sources.settings.entities.botania]
				babylon_weapon = true
				mana_burst = true

			[light_sources.settings.entities.items_displayed]
				item_display = true

			[light_sources.settings.entities.vinery]
				wandering_winemaker = true
				mule = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				naga = true
				jungle_skeleton = true
				skull = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.smallships]
				cog = true
				brigg = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				end_fish = true
				end_slime = true
				shadow_walker = true
				cubozoa = true

			[light_sources.settings.entities.deeperdarker]
				sculk_leech = true
				shattered = true
				sculk_centipede = true
				sculk_snapper = true

			[light_sources.settings.entities.grapplemod]
				grapplehook = true

