#General configuration settings
[client]
	#Show underline on link
	underlineLink = true
	#Enable color on link
	colorLink = true
	#Color of the link
	#Valid colors: 
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	colorName = "blue"
	#Prevent link detection issues with message containing formatting codes
	#Required for received messages that contains it
	convertFormattingCode = true
	#Show raw message for debugging
	debugMessage = false
