name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22be0001d935ef172d44f8ae018c379494b96fb51fc7a72441a39b2c7b566c11"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
