name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33554236b94efc36507b1b3783f4aeb2b89bff5c4e1348f3ba96c92f8bfad4e0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
