name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee88dc5a38e1d75d7c3d6fceeccb637456b92fbfaef33afd4f1329dc53877ed"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
