name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c6627645875aee2a18989fdd5cd6f52fbb72faa356483eddcf468490dc25058"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
