name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5187e43d32e8069fd6dff73e4bca370373e82524c8e57cb36bb06583e51fe71"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
