name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f062dd9eebdfa0b58f0d154064d79b13ce1ee9995433d3b41863cd99fd55acc9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
