name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b31bf6b1ed029f34cd0354caeae232799e2c7e55bf854425f60eef9b64b82f2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
