name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3895adb66b695eca71cfa9a16055efce94100c25ce9777681e288d458d7ba2aa"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
