name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7f4354709154973ce6d7fa0d5c9a80dac6fdabdfeabc1745a68c6c8290b9463"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
