name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d2a527f819a83f37ca54b5756c7b14a2eac0bcd24d1e3caa6c98dc5379f18d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
