name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5feb8161883bd3e05e558171419be23a90cfe92c6d2035258d76ce16da6c2ba8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
