name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c500c6c7c120aef8f01915be2c691fd1b02857b281671c30680222234864ca0d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
