name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63d7104d50d3fad3ba2a033371a77b3a2e734ae600afc6617160362a968720fe"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
