name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb9bf2522560488ca123d78ef83dfda82a7359f41863e35ad82a0514b803e131"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
