name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a52e39b55d04a786ecced5dac4f6b5d3370e0e59e2f4990563ee22120403a1b4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
