// priority: 0

// Visit the wiki for more info - https://kubejs.com/

// renames
ClientEvents.lang('en_us', event => {
    const rename = (item, newName) => {event.renameItem(item, newName)}
    rename ( 'deeperdarker:warden_pickaxe', "Echo Pickaxe" )
    rename ( 'deeperdarker:warden_shovel', "Echo Shovel" )
    rename ( 'deeperdarker:warden_axe', "Echo Axe" )
    rename ( 'deeperdarker:warden_hoe', "Echo Hoe" )
    rename ( 'deeperdarker:warden_sword', "Echo Sword" )
    rename ( 'deeperdarker:warden_helmet', "Echo Helmet" )
    rename ( 'deeperdarker:warden_chestplate', "Echo Chestplate" )
    rename ( 'deeperdarker:warden_leggings', "Echo Leggings" )
    rename ( 'deeperdarker:warden_boots', "Echo Boots" )
    rename ( 'beautify:rope', "Decorative String" )
    rename ( 'heartstone:heartstone', "Connecting Crystal" )
    rename ( 'simplyswords:iron_greathammer', "Iron Warhammer" )
    rename ( 'simplyswords:gold_greathammer', "Golden Warhammer" )
    rename ( 'simplyswords:diamond_greathammer', "Diamond Warhammer" )
    rename ( 'simplyswords:netherite_greathammer', "Netherite Warhammer" )
    rename ( 'simplyswords:runic_greathammer', "Runic Warhammer" )
    rename ( 'brewery:rope', "Brewery Rope" )
})

ItemEvents.tooltip(event => {
    event.add('minecraft:respawn_anchor', '§6Can be used in any dimension, including the Overworld.')
    event.add('endanchor:end_anchor', '§6See questbook for recipe and usage.')
    event.add('minecraft:soul_campfire', '§6Serves as a deterrent for the Undead when lit as a signal atop a hay block.')
    event.add('malum:runewood_obelisk', '§6A hallowed beacon of light. Stops the spread of Evil.')
})

REIEvents.hide('item', event => {
    event.hide('simplyswords:iron_spear' )
    event.hide('simplyswords:gold_spear' )
    event.hide('simplyswords:diamond_spear' )
    event.hide('simplyswords:netherite_spear' )
    event.hide('simplyswords:runic_spear' )
    event.hide('sophisticatedbackpacks:chipped/botanist_workbench_upgrade' )
    event.hide('sophisticatedbackpacks:chipped/glassblower_upgrade' )
    event.hide('sophisticatedbackpacks:chipped/carpenters_table_upgrade' )
    event.hide('sophisticatedbackpacks:chipped/loom_table_upgrade' )
    event.hide('sophisticatedbackpacks:chipped/mason_table_upgrade' )
    event.hide('sophisticatedbackpacks:chipped/alchemy_bench_upgrade' )
    event.hide('sophisticatedbackpacks:chipped/tinkering_table_upgrade' )
    event.hide('sophisticatedbackpacks:inception_upgrade' )
    event.hide('immersive_aircraft:gyrodyne' )
    event.hide('immersive_aircraft:quadrocopter' )
    event.hide('gag:time_sand_pouch' )
    event.hide('gag:escape_rope' )
    event.hide('gag:energized_hearthstone' )
    event.hide('phonos:white_audio_cable' )
    event.hide('phonos:orange_audio_cable' )
    event.hide('phonos:magenta_audio_cable' )
    event.hide('phonos:light_blue_audio_cable' )
    event.hide('phonos:yellow_audio_cable' )
    event.hide('phonos:lime_audio_cable' )
    event.hide('phonos:pink_audio_cable' )
    event.hide('phonos:gray_audio_cable' )
    event.hide('phonos:light_gray_audio_cable' )
    event.hide('phonos:cyan_audio_cable' )
    event.hide('phonos:purple_audio_cable' )
    event.hide('phonos:blue_audio_cable' )
    event.hide('phonos:brown_audio_cable' )
    event.hide('phonos:green_audio_cable' )
    event.hide('phonos:red_audio_cable' )
    event.hide('phonos:black_audio_cable' )
    event.hide('phonos:headset' )
    event.hide('phonos:portable_radio' )
    event.hide('phonos:portable_record_player' )
    event.hide('createaddition:electrum_amulet' )
    event.hide('ad_astra:iron_plate' )
    event.hide('ad_astra:iron_rod' )
    event.hide('ad_astra:compressor' )
    event.hide('ad_astra:coal_generator' )
    event.hide('ad_astra:water_pump' )
    event.hide('farmersdelight:rope' )
    event.hide('ad_astra:jet_suit_helmet' )
    event.hide('ad_astra:jet_suit' )
    event.hide('ad_astra:jet_suit_pants' )
    event.hide('ad_astra:jet_suit_boots' )
    event.hide('darkutils:vector_plate_fast' )
    event.hide('darkutils:vector_plate_extreme' )
    event.hide('darkutils:vector_plate_ultra' )
    event.hide('paladins:wooden_great_hammer' )
    event.hide('paladins:stone_great_hammer' )
    event.hide('paladins:iron_great_hammer' )
    event.hide('paladins:golden_great_hammer' )
    event.hide('paladins:diamond_great_hammer' )
    event.hide('paladins:netherite_great_hammer' )
    event.hide('paladins:stone_claymore' )
    event.hide('paladins:iron_claymore' )
    event.hide('paladins:golden_claymore' )
    event.hide('paladins:diamond_claymore' )
    event.hide('paladins:netherite_claymore' )
    event.hide('createaddition:zinc_sheet' )
    event.hide('onlyhammersandexcavators:wooden_hammer' )
    event.hide('onlyhammersandexcavators:iron_hammer' )
    event.hide('onlyhammersandexcavators:gold_hammer' )
    event.hide('onlyhammersandexcavators:diamond_hammer' )
    event.hide('onlyhammersandexcavators:netherite_hammer' )
    event.hide('onlyhammersandexcavators:lapis_hammer' )
    event.hide('onlyhammersandexcavators:emerald_hammer' )
    event.hide('onlyhammersandexcavators:redstone_hammer' )
    event.hide('onlyhammersandexcavators:wooden_excavator' )
    event.hide('onlyhammersandexcavators:iron_excavator' )
    event.hide('onlyhammersandexcavators:gold_excavator' )
    event.hide('onlyhammersandexcavators:diamond_excavator' )
    event.hide('onlyhammersandexcavators:netherite_excavator' )
    event.hide('onlyhammersandexcavators:lapis_excavator' )
    event.hide('onlyhammersandexcavators:emerald_excavator' )
    event.hide('onlyhammersandexcavators:redstone_excavator' )
    event.hide('sophisticatedbackpacks:stack_upgrade_tier_1' )
    event.hide('sophisticatedbackpacks:stack_upgrade_tier_2' )
    event.hide('sophisticatedbackpacks:stack_upgrade_tier_3' )
    event.hide('sophisticatedbackpacks:stack_upgrade_tier_4' )
    event.hide('vinery:apple_bag' )
    event.hide('naturalist:cooked_egg' )
    event.hide('extraalchemy:empty_ring' )
    event.hide('extraalchemy:potion_ring' )
    event.hide('malum:copper_nugget' )
    event.hide('ae2:quantum_ring' )
    event.hide('ae2:quantum_link' )
    event.hide('ae2:singularity' )
    event.hide('ae2:quantum_entangled_singularity' )
} )
