name = "Comprehensive"
author = "kilo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
